backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - label: "Exhibitions"
  - name: "exhibitions"
  - create: true
  - folder: "src/markdown/exhibition-data"
  - slug: "{{exhibition-title}-{artwork-title}}"
  - fields:
      - {
          label: "Exhibition Title",
          name: "exhibition-title",
          widget: "string",
          required: true,
        }
      - { label: "Venue", name: "venue", widget: "string", required: true }
      - { label: "Year", name: "year", widget: "string", required: true }
      - { label: "Images", name: "images", widget: "list" }
      - fields:
          - { label: "Image", name: "image", widget: "image", required: true }
          - {
              label: "Image Description",
              hint: "required for screen readers",
              name: "image-alt",
              widget: "string",
              required: true,
            }
          - {
              label: "Title",
              name: "artwork-title",
              widget: "string",
              required: true,
            }
          - {
              label: "ID",
              name: "id",
              widget: "string",
              default: "WCHS0000",
              hint: "number entries with consistent naming convention; each entry MUST be unique",
              required: true,
            }
          - {
              label: "Materials",
              name: "artwork-materials",
              widget: "string",
              required: false,
            }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Information Page"
        name: "info"
        create: true
        file: "src/markdown/pages-data/info.md"
        fields:
          - {
              label: "Information Page Content",
              name: "info-content",
              widget: "markdown",
            }
      - label: "Contact Page"
        create: true
        name: "contact-page"
        file: "src/markdown/pages-data/contact.md"
        fields:
          - {
              label: "Contact Page Content",
              name: "contact-content",
              widget: "markdown",
            }
          - label: "Email Contacts"
            name: "email-contact"
            widget: "list"
            fields:
              - {
                  label: "Contact Name",
                  name: "contact-name",
                  widget: "string",
                }
              - { label: "Email", name: "name", widget: "string" }
