backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

site_url: https://kind-clarke-8528a2.netlify.com/

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - label: "Exhibitions"
    name: "exhibitions"
    create: true
    folder: "src/pages/markdown/exhibitions"
    slug: "{{year}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "exhibition",
        }
      - {
          label: "Exhibition Title",
          name: "title",
          widget: "string",
          required: true,
        }
      - { label: "Venue", name: "venue", widget: "string", required: true }
      - { label: "Year", name: "year", widget: "string", required: true }
      - {
          label: "ID",
          name: "id",
          widget: "string",
          default: "XXXX-0000",
          hint: "each entry MUST be unique",
          required: true,
        }
      - {
          label: "Exhibition Images",
          name: "exhibition-images",
          widget: "list",
          fields:
            [
              {
                label: "Title",
                name: "artwork-title",
                widget: "string",
                required: true,
              },
              {
                label: "Image",
                name: "image",
                widget: "image",
                required: true,
              },
              {
                label: "Image Description",
                hint: "required for screen readers",
                name: "image-alt",
                widget: "string",
                required: true,
              },
              {
                label: "Materials",
                name: "artwork-materials",
                widget: "string",
                required: false,
              },
              {
                label: "ID",
                name: "id",
                widget: "string",
                default: "IMG0000",
                hint: "each entry MUST be unique",
                required: true,
              },
            ],
          required: true,
        }
  - label: "Pages"
    name: "pages"
    create: true
    folder: "src/pages/markdown/page-data"
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "page",
        }
      - { label: "Page Title", name: "title", widget: "string", required: true }
      - {
          label: "ID",
          name: "id",
          widget: "string",
          hint: "each entry MUST be unique",
          default: "page000",
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
